version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: stopcontainer.sh
      timeout: 300
  AfterInstall:
    - location: restart_codedeploy_agent.sh
      timeout: 300
    - location: codedeploy_status_check.sh
      timeout: 300
  ApplicationStart:
    - location: startcontainer.sh  # Start container during ApplicationStart
      timeout: 300
    - location: check_logs.sh
      timeout: 300
