version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python --version
      - pip install --upgrade pip
      - pip install flask_sqlalchemy
      - pip install -r requirements.txt
      - pip freeze

  build:
    commands:
      - echo "Build is completed..."
     
