version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python --version
      - pip install --upgrade pip
      - pip install flask_sqlalchemy
      - sed -i 's/\u200b//g' requirements.txt
      - cat -A requirements.txt
      - pip install -r requirements.txt -v
      - pip freeze

  build:
    commands:
      - echo "Build is completed..."
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 010438505789.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Login successful!"
      
      # Build Docker image with 'latest' tag (You can also add a dynamic tag if needed)
      - docker build -t infraoutput_vcloud .

      # Tag the image for ECR
      - docker tag infraoutput_vcloud:latest 010438505789.dkr.ecr.ap-south-1.amazonaws.com/mallapp_vcloud:latest
      - docker push 010438505789.dkr.ecr.ap-south-1.amazonaws.com/infraoutput_vcloud:latest

  post_build:
    commands:
      - echo "Build completed and Docker image tagged for ECR."
      # Run the Flask application
      - echo "Starting the Flask application..."
      - nohup python app.py &    
